[package]
name = "bevy_geometry"
version = "0.4.0"
authors = [
    "Bevy Contributors <bevyengine@gmail.com>",
    "Aevyrie Roessler <aevyrie@gmail.com>",
]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy_math = { path = "../bevy_math", version = "0.4.0" }
bevy_reflect = { path = "../bevy_reflect", version = "0.4.0" }
