name: Docs Improvement
description: Help us write better docs to catch common issues!
title: ''
labels: [C-Docs, S-Needs-Triage]
assignees: ''
body:
  - type: textarea
    id: docs
    attributes:
      label: How can Bevy's documentation be improved?
      description: |
        Provide a link to the documentation and describe how it could be improved. In what ways is it incomplete, incorrect, or misleading?

        If you have suggestions on exactly what the new docs should say, feel free to include them here. Or alternatively, make the changes yourself and [create a pull request](https://bevyengine.org/learn/book/contributing/code/) instead.
    validations:
      required: true